import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        secondary: "#835500",
        tertiaryContainer: "#6f7678",
        onPrimaryFixed: "#410007",
        onTertiaryFixed: "#161d1f",
        onPrimaryFixedVariant: "#92001c",
        secondaryContainer: "#feae2c",
        surfaceBright: "#f9f9f9",
        primaryFixedDim: "#ffb3b1",
        onBackground: "#1a1c1c",
        onSecondary: "#ffffff",
        onSecondaryFixed: "#291800",
        surfaceContainerHigh: "#e8e8e8",
        tertiaryFixedDim: "#c1c8ca",
        surfaceDim: "#dadada",
        outline: "#8f6f6e",
        secondaryFixedDim: "#ffb955",
        inverseSurface: "#2f3131",
        onSurface: "#1a1c1c",
        background: "#f9f9f9",
        inverseOnSurface: "#f0f1f1",
        onSecondaryContainer: "#6b4500",
        errorContainer: "#ffdad6",
        surfaceTint: "#bb162c",
        surfaceVariant: "#e2e2e2",
        onError: "#ffffff",
        onSecondaryFixedVariant: "#633f00",
        onPrimaryContainer: "#fffbff",
        outlineVariant: "#e4bebc",
        secondaryFixed: "#ffddb4",
        onSurfaceVariant: "#5b403f",
        tertiaryFixed: "#dde4e6",
        primary: "#b7122a",
        surfaceContainer: "#eeeeee",
        onTertiary: "#ffffff",
        inversePrimary: "#ffb3b1",
        error: "#ba1a1a",
        surfaceContainerLow: "#f3f3f3",
        onTertiaryFixedVariant: "#41484a",
        onTertiaryContainer: "#f9fdff",
        onPrimary: "#ffffff",
        surface: "#f9f9f9",
        tertiary: "#565d5f",
        primaryContainer: "#db313f",
        surfaceContainerHighest: "#e2e2e2",
        surfaceContainerLowest: "#ffffff",
        onErrorContainer: "#93000a",
        primaryFixed: "#ffdad8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        lg: "24px",
        containerMax: "1200px",
        sm: "12px",
        base: "8px",
        xl: "40px",
        gutter: "16px",
        xs: "4px",
      },
      fontFamily: {
        displayLg: ["DM Sans", "sans-serif"],
        titleMd: ["DM Sans", "sans-serif"],
        headlineLgMobile: ["DM Sans", "sans-serif"],
        headlineLg: ["DM Sans", "sans-serif"],
        bodyLg: ["DM Sans", "sans-serif"],
        bodySm: ["DM Sans", "sans-serif"],
        labelMd: ["DM Sans", "sans-serif"],
      },
      fontSize: {
        displayLg: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        titleMd: ["20px", { lineHeight: "28px", fontWeight: "600" }],
        headlineLgMobile: ["24px", { lineHeight: "32px", fontWeight: "700" }],
        headlineLg: ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        bodyLg: ["16px", { lineHeight: "24px", fontWeight: "400" }],
        bodySm: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        labelMd: ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
